title: 'La Vorágine'
tagline: 'Un laboratorio de edición digital'
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  La Vorágine es una editorial independiente de Barcelona, dedicada a la publicación de libros deliciosamente extraños, que campan en las fronteras entre géneros, esos lugares peligrosos y propensos a la belleza. Nuestros libros son (casi siempre) primeras traducciones de autores esenciales y nunca (o muy poco) publicados en lengua española, en ediciones que procuramos sean completas, accesibles y cuidadas..
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

collections:
  libros:
    output: true
    permalink: /libros/:path/

#social media

facebook_url: 'https://www.facebook.com/LibrosdelaVoragine/'
twitter_url: 'https://twitter.com/voraginebooks'
linkedin_url:
pinterest_url:
instagram_url:
