title: 'La Vorágine'
tagline: 'Un laboratorio de edición digital'
email: info@librosdelavoragine.com
description: >- # this means to ignore newlines until "baseurl:"
  Libros de la vorágine es una micro editorial independiente, con un pie en Barcelona y otro en Santiago de Chile, nacida el año 2011 y cuya historia se ha materializado en quince títulos.
  
  Ofrecemos un catálogo heterogéneo, editado principalmente en castellano (aunque hayamos publicado también algunos títulos en catalán), hecho de clásicos olvidados, ensayos urgentes, y ficción reveladora. Publicamos libros no editados anteriormente en castellano, en traducciones cuidadas, y con enfasis particular en la accesibilidad.

  A pesar de la pluralidad de géneros y temáticas, nuestras publicaciones tienen un común denominador: la voluntad de despertar el asombro en el lector y promover la edición libre desde los márgenes de la cultura."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

collections:
  libros:
    output: true
    permalink: /libros/:path/
  proximamente:
    output: true
    permalink: /proximamente/:path/

#social media

facebook_url: 'https://www.facebook.com/LibrosdelaVoragine/'
twitter_url: 'https://twitter.com/voraginebooks'
linkedin_url:
pinterest_url:
instagram_url:
